name: Deploy BeerTaste
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install && npm run build
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SECRET_SERVER_IP }}
          port: ${{ secrets.SECRET_SSH_PORT }}
          username: ${{ secrets.SECRET_SSH_USER }}
          key: ${{ secrets.SECRET_SSH_KEY }}
          source: "dist/*"
          target: "${{ secrets.SECRET_DEPLOY_PATH }}/"
